import {Action} from "../actions/Action";
import StoreBase from "./StoreBase";
import log from "../Logger";
import {stimo, stimo_get, stimo_set} from "stimo";
import {List} from "immutable";
import {Point} from "../util/Geometry";


// use stimo instead of immutable.js records to get proper typing
@stimo
export class LifeCell {

  constructor(alive: boolean, neighborCount: number) {
    this.setAlive(alive).setNeighborCount(neighborCount);
  }

  /** method implemenation  will be generated by stimo decorator */
  @stimo_get get alive(): boolean {
    return null;
  };

  //noinspection JSUnusedLocalSymbols
  /** method implemenation will be generated by stimo decorator */
  @stimo_set setAlive(newValue: boolean): LifeCell {
    return null;
  };

  @stimo_get get neighborCount(): number {
    return null;
  };

  //noinspection JSUnusedLocalSymbols
  @stimo_set setNeighborCount(newValue: number): LifeCell {
    return null;
  };
}


function getLifeCell(cells: List<List<LifeCell>>, x: number, y: number): LifeCell {
  return cells.get(y).get(x);
}

function setLifeCell(cells: List<List<LifeCell>>, x: number, y: number, newContent: LifeCell): List<List<LifeCell>> {
  return cells.set(y, cells.get(y).set(x, newContent));
}

const NEIGHBOR_OFFSETS: Point[] = [new Point(-1, -1), new Point(-1, 0), new Point(-1, 1), new Point(0, -1), new Point(0, 1), new Point(1, -1), new Point(1, 0), new Point(1, 1)];

/**
 * models a Game of Life Board with current neighbor count
 */
@stimo
export class Board {

  @stimo_get get maxX(): number {
    return null;
  };

  //noinspection JSUnusedLocalSymbols
  @stimo_set setMaxX(newValue: number): Board {
    return null;
  };

  @stimo_get get maxY(): number {
    return null;
  };

  //noinspection JSUnusedLocalSymbols
  @stimo_set setMaxY(newValue: number): Board {
    return null;
  };

  @stimo_get get cells(): List<List<LifeCell>> {
    return null;
  };

  //noinspection JSUnusedLocalSymbols
  @stimo_set setCells(newValue: List<List<LifeCell>>): Board {
    return null;
  };

  constructor(maxX: number, maxY: number) {
    this.initSize(maxX, maxY).initEmpty();
  }

  set(x: number, y: number, value: boolean): Board {
    const newCells = this.cells.withMutations((cells: List<List<LifeCell>>) => {
      const lifeCell = getLifeCell(cells, x, y);
      if (lifeCell.alive !== value) {
        cells = setLifeCell(cells, x, y, lifeCell.setAlive(value));
        cells = this.adjustNeighbors(cells, x, y, value ? 1 : -1);
      }
      return cells;
    });
    return this.setCells(newCells);
  }

  /**
   * make sure this is always called inside withMutations !
   * adjust all neighbor counts of the given life by adding delta
   * @param cells cells to adjust neigbors in
   * @param x xpos of life to adjust
   * @param y ypos of life to adjust
   * @param delta +/- 1 neighbor to adjust
   */
  private adjustNeighbors(cells: List<List<LifeCell>>, x: number, y: number, delta: number): List<List<LifeCell>> {
    let result: List<List<LifeCell>> = cells;
    for (const d of NEIGHBOR_OFFSETS) {
      const nx = x + d.x;
      const ny = y + d.y;
      if (nx >= 0 && nx < this.maxX && ny >= 0 && ny < this.maxY) {
        const entry = getLifeCell(result, nx, ny);
        result = setLifeCell(result, nx, ny, entry.setNeighborCount(entry.neighborCount + delta));
      }
    }
    return result;
  }

  /**
   * initializes cell with randomly set life
   */
  public initRandom(): Board {
    return this.init(cell => cell.setAlive(Math.random() < 0.3));
  }

  /**
   * initializes cell with regular pattern for better reproducability
   */
  public initRegular(): Board {
    return this.init((cell, x, y) => cell.setAlive((x + this.maxX * y) % 3 === 0));
  }

  initEmpty(): Board {
    return this.init(cell => new LifeCell(false, 0));
  }

  private init(callback: (cell: LifeCell, x?: number, y?: number) => LifeCell): Board {
    let cells = this.cells.withMutations((cells: List<List<LifeCell>>) => {
      for (let y = 0; y < this.maxX; y++) {
        for (let x = 0; x < this.maxX; x++) {
          const cell = getLifeCell(cells, x, y);
          cells = setLifeCell(cells, x, y, callback(cell, x, y));
        }
      }
      for (let y = 0; y < this.maxX; y++) {
        for (let x = 0; x < this.maxX; x++) {
          const cell = getLifeCell(cells, x, y);
          if (cell.alive) {
            cells = this.adjustNeighbors(cells, x, y, 1);
          }
        }
      }
    });
    return this.setCells(cells);
  }


  /**
   * calculate next life generation in cell
   */
  public calculateNextGeneration(): Board {
    const lastCells = this.cells;
    const newCells = this.cells.withMutations((cells: List<List<LifeCell>>) => {
      // remember cells for last neighborcount
      for (let y = 0; y < this.maxX; y++) {
        for (let x = 0; x < this.maxX; x++) {
          const cell = getLifeCell(lastCells, x, y);
          const nc = cell.neighborCount;
          const isAlive = cell.alive;
          if (isAlive && (nc < 2 || nc > 3)) {
            // < 2 || > 3 neighbors --> died
            const entry = getLifeCell(cells, x, y);
            cells = setLifeCell(cells, x, y, entry.setAlive(false));
            cells = this.adjustNeighbors(cells, x, y, -1);
          } else if (!isAlive && nc === 3) {
            const entry = getLifeCell(cells, x, y);
            // === 3 neighbors -> born
            cells = setLifeCell(cells, x, y, entry.setAlive(true));
            cells = this.adjustNeighbors(cells, x, y, 1);
          }
        }
      }
      return cells;
    });
    return this.setCells(newCells);
  }

  public cell(x: number, y: number): LifeCell {
    return getLifeCell(this.cells, x, y);
  }

  public initSize(x: number, y: number): Board {
    let list = List<List<LifeCell>>().setSize(y);
    list.forEach((row, index) => {
      list = list.set(index, List<LifeCell>().setSize(x));
    });
    return this.setMaxX(x).setMaxY(y).setCells(list);
  }
}

export class ModelStore extends StoreBase {

  private _board: Board;
  private static DEFAULT_SIZE: number = 5;

  constructor() {
    super();
    this._board = new Board(ModelStore.DEFAULT_SIZE, ModelStore.DEFAULT_SIZE).initEmpty();
  }

  public cell(x: number, y: number): LifeCell {
    return this._board.cell(x, y);
  }

  public get board(): Board {
    return this._board;
  }

  accept(action: Action): void {
    log.info("ModelStore accepting", action);
    switch (action.type) {
      case "clear":
        this._board = this._board.initEmpty();
        break;
      case "initRandom":
        this._board = this._board.initRandom();
        break;
      case "initRegular":
        this._board = this._board.initRegular();
        break;
      case "size":
        this._board = this._board.initSize(action.payload, action.payload).initEmpty();
        break;
      case "next":
        this._board = this._board.calculateNextGeneration();
        break;
      case "set":
        const {x, y, value} = action.payload;
        this._board = this._board.set(x, y, value);
    }
    this.notify(action.type);
  }
}

export default new ModelStore();